version: '3.9'

services:
  postgres-db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: docker123
      POSTGRES_DB: images
    ports: 
     - '5434:5432'
