spring: 
  datasource:
    url: jdbc://postgresql://127.0.0.1:5434/images
    username: development
    password: docker123
    
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
 